<a href="https://colab.research.google.com/github/Carlos-jw/Fichas_LDC/blob/main/ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install requests beautifulsoup4 lxml pandas openpyxl

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.4.22)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

In [ ]:
url = "https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/"

response = requests.get(url)

print(response.status_code)

200

In [ ]:
soup = BeautifulSoup(response.text, "lxml")

print(soup.title.text)

Guía de actividades para la reunión Vida y Ministerio Cristianos

In [ ]:
links = soup.find_all("a")

print("Cantidad de links:", len(links))

for link in links[:311]:
    print(link.get("href"))

Cantidad de links: 311
/es/
https://hub.jw.org/home/es
/es/b%C3%BAsquedas/
/es/
/es/ense%C3%B1anzas-b%C3%ADblicas/
/es/ense%C3%B1anzas-b%C3%ADblicas/preguntas/
/es/ense%C3%B1anzas-b%C3%ADblicas/textos-biblicos/
/es/ense%C3%B1anzas-b%C3%ADblicas/programa-clases-particulares-biblia/
/es/ense%C3%B1anzas-b%C3%ADblicas/ayudas-estudiar-biblia/
/es/ense%C3%B1anzas-b%C3%ADblicas/felicidad-paz-interior/
/es/ense%C3%B1anzas-b%C3%ADblicas/familia/
/es/ense%C3%B1anzas-b%C3%ADblicas/j%C3%B3venes/
/es/ense%C3%B1anzas-b%C3%ADblicas/ni%C3%B1os/
/es/ense%C3%B1anzas-b%C3%ADblicas/fe-en-dios/
/es/ense%C3%B1anzas-b%C3%ADblicas/ciencia/
/es/ense%C3%B1anzas-b%C3%ADblicas/historia-biblia/
/es/biblioteca/
/es/biblioteca/biblia/
/es/biblioteca/libros/
/es/biblioteca/folletos/
/es/biblioteca/tratados/
/es/biblioteca/articulos/
/es/biblioteca/revistas/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/
/es/biblioteca/ministerio-del-reino/
/es/biblioteca/programas/
/es/biblioteca/%C3%ADndices/
/es/biblioteca/pautas/
/es/biblioteca/videos/#es/categories/VODStudio
/es/biblioteca/videos/
/es/biblioteca/m%C3%BAsica-canciones/
/es/biblioteca/audio-representaciones-dram%C3%A1ticas/
/es/biblioteca/lecturas-b%C3%ADblicas-dramatizadas/
https://wol.jw.org/wol/finder?wtlocale=S
/es/noticias/
/es/testigos-de-jehov%C3%A1/
/es/testigos-de-jehov%C3%A1/preguntas-frecuentes/
/es/testigos-de-jehov%C3%A1/solicite-una-visita/
/es/testigos-de-jehov%C3%A1/datos-de-contacto/
/es/testigos-de-jehov%C3%A1/visitas-a-betel/
/es/testigos-de-jehov%C3%A1/reuniones/
/es/testigos-de-jehov%C3%A1/conmemoracion/
/es/testigos-de-jehov%C3%A1/asambleas-anuales/
/es/testigos-de-jehov%C3%A1/qui%C3%A9nes-somos-y-qu%C3%A9-hacemos/
/es/testigos-de-jehov%C3%A1/experiencias/
/es/testigos-de-jehov%C3%A1/por-todo-el-mundo/
https://donate.jw.org/es
https://hub.jw.org/home/es
/es/
/es/choose-language?locale=es&prefer=lang&docid=1011529
https://hub.jw.org/home/es
/es/
/es/ense%C3%B1anzas-b%C3%ADblicas/
/es/ense%C3%B1anzas-b%C3%ADblicas/
/es/ense%C3%B1anzas-b%C3%ADblicas/preguntas/
/es/ense%C3%B1anzas-b%C3%ADblicas/textos-biblicos/
/es/ense%C3%B1anzas-b%C3%ADblicas/programa-clases-particulares-biblia/
/es/ense%C3%B1anzas-b%C3%ADblicas/ayudas-estudiar-biblia/
/es/ense%C3%B1anzas-b%C3%ADblicas/felicidad-paz-interior/
/es/ense%C3%B1anzas-b%C3%ADblicas/familia/
/es/ense%C3%B1anzas-b%C3%ADblicas/j%C3%B3venes/
/es/ense%C3%B1anzas-b%C3%ADblicas/ni%C3%B1os/
/es/ense%C3%B1anzas-b%C3%ADblicas/fe-en-dios/
/es/ense%C3%B1anzas-b%C3%ADblicas/ciencia/
/es/ense%C3%B1anzas-b%C3%ADblicas/historia-biblia/
/es/biblioteca/
/es/biblioteca/
/es/biblioteca/biblia/
/es/biblioteca/libros/
/es/biblioteca/folletos/
/es/biblioteca/tratados/
/es/biblioteca/articulos/
/es/biblioteca/revistas/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/
/es/biblioteca/ministerio-del-reino/
/es/biblioteca/programas/
/es/biblioteca/%C3%ADndices/
/es/biblioteca/pautas/
/es/biblioteca/videos/#es/categories/VODStudio
/es/biblioteca/videos/
/es/biblioteca/m%C3%BAsica-canciones/
/es/biblioteca/audio-representaciones-dram%C3%A1ticas/
/es/biblioteca/lecturas-b%C3%ADblicas-dramatizadas/
https://wol.jw.org/wol/finder?wtlocale=S
/es/noticias/
/es/testigos-de-jehov%C3%A1/
/es/testigos-de-jehov%C3%A1/
/es/testigos-de-jehov%C3%A1/preguntas-frecuentes/
/es/testigos-de-jehov%C3%A1/solicite-una-visita/
/es/testigos-de-jehov%C3%A1/datos-de-contacto/
/es/testigos-de-jehov%C3%A1/visitas-a-betel/
/es/testigos-de-jehov%C3%A1/reuniones/
/es/testigos-de-jehov%C3%A1/conmemoracion/
/es/testigos-de-jehov%C3%A1/asambleas-anuales/
/es/testigos-de-jehov%C3%A1/qui%C3%A9nes-somos-y-qu%C3%A9-hacemos/
/es/testigos-de-jehov%C3%A1/experiencias/
/es/testigos-de-jehov%C3%A1/por-todo-el-mundo/
https://donate.jw.org/es
/es/biblioteca/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2026-mwb/
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202609&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202609&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202609&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202609&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202609&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202609&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202609&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202609&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/julio-agosto-2026-mwb/
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202607&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202607&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202607&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202607&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202607&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202607&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202607&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202607&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202607&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
/es/biblioteca/guia-actividades-reunion-testigos-jehova/julio-agosto-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/julio-agosto-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/julio-agosto-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/mayo-junio-2026-mwb/
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202605&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202605&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202605&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202605&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202605&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202605&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202605&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202605&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202605&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
/es/biblioteca/guia-actividades-reunion-testigos-jehova/mayo-junio-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/mayo-junio-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/mayo-junio-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/marzo-abril-2026-mwb/
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202603&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202603&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202603&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202603&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202603&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202603&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202603&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202603&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202603&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
/es/biblioteca/guia-actividades-reunion-testigos-jehova/marzo-abril-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/marzo-abril-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/marzo-abril-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/enero-febrero-2026-mwb/
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202601&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202601&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202601&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202601&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202601&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202601&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202601&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202601&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202601&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
/es/biblioteca/guia-actividades-reunion-testigos-jehova/enero-febrero-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/enero-febrero-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/enero-febrero-2026-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/noviembre-diciembre-2025-mwb/
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202511&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202511&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202511&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202511&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202511&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202511&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202511&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202511&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202511&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
/es/biblioteca/guia-actividades-reunion-testigos-jehova/noviembre-diciembre-2025-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/noviembre-diciembre-2025-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/noviembre-diciembre-2025-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2025-mwb/
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202509&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202509&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202509&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202509&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202509&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202509&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202509&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202509&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202509&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2025-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2025-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2025-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/julio-agosto-2025-mwb/
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202507&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202507&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202507&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202507&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202507&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202507&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202507&output=html&pub=mwb&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202507&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202507&output=html&pub=mwb&fileformat=MP3%2CAAC&alllangs=0&langwritten=S&txtCMSLang=S
/es/biblioteca/guia-actividades-reunion-testigos-jehova/julio-agosto-2025-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/julio-agosto-2025-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/julio-agosto-2025-mwb/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/mwbr202609/
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202609&output=html&pub=mwbr&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202609&output=html&pub=mwbr&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S
/es/biblioteca/guia-actividades-reunion-testigos-jehova/mwbr202609/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/mwbr202609/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/mwbr202609/
/es/biblioteca/guia-actividades-reunion-testigos-jehova/mwbr202607/
https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?issue=202607&output=html&pub=mwbr&fileformat=PDF%2CEPUB%2CJWPUB%2CRTF%2CTXT%2CBRL%2CBES%2CDAISY&alllangs=0&langwritten=S&txtCMSLang=S

In [ ]:
base = "https://www.jw.org"

publicaciones_full = [
    base + p for p in publicaciones
]

publicaciones_full[:5]

['https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2026-mwb/',
 'https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2025-mwb/',
 'https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/noviembre-diciembre-2025-mwb/',
 'https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/mayo-junio-2026-mwb/',
 'https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/marzo-abril-2026-mwb/']

In [ ]:
df_issues = pd.DataFrame({
    "issue_url": publicaciones_full
})

df_issues.head()

                                           issue_url
0  https://www.jw.org/es/biblioteca/guia-activida...
1  https://www.jw.org/es/biblioteca/guia-activida...
2  https://www.jw.org/es/biblioteca/guia-activida...
3  https://www.jw.org/es/biblioteca/guia-activida...
4  https://www.jw.org/es/biblioteca/guia-activida...

In [ ]:
issue_url = publicaciones_full[0]

print(issue_url)

https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2026-mwb/

In [ ]:
html_issue = requests.get(issue_url).text

soup_issue = BeautifulSoup(html_issue, "lxml")

In [ ]:
print(soup_issue.title.text)

Guía de actividades para la reunión Vida y Ministerio Cristianos

In [ ]:
for tag in soup_issue.find_all(["h1", "h2", "h3"]):
    print(tag.text.strip())

Testigos de Jehová
Septiembre y octubre de 2026
GUÍA DE ACTIVIDADES
                  Septiembre y octubre de 2026
7-13 de septiembre
14-20 de septiembre
21-27 de septiembre
28 de septiembre a 4 de octubre
5-11 de octubre
12-18 de octubre
19-25 de octubre
26 de octubre a 1 de noviembre
Seleccione un idioma
Compartir

In [ ]:
weeks_data = []

for a in soup_issue.find_all("a", href=True):

    texto = a.text.strip()
    href = a["href"]

    # detectar semanas
    if re.search(r"\d{1,2}-\d{1,2}\sde", texto):

        weeks_data.append({
            "semana": texto,
            "url": base + href
        })

len(weeks_data)

6

In [ ]:
for w in weeks_data[:10]:
    print(w)

{'semana': '7-13 de septiembre', 'url': 'https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2026-mwb/Vida-y-Ministerio-Cristianos-7-a-13-de-septiembre-de-2026/'}
{'semana': '14-20 de septiembre', 'url': 'https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2026-mwb/Vida-y-Ministerio-Cristianos-14-a-20-de-septiembre-de-2026/'}
{'semana': '21-27 de septiembre', 'url': 'https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2026-mwb/Vida-y-Ministerio-Cristianos-21-a-27-de-septiembre-de-2026/'}
{'semana': '5-11 de octubre', 'url': 'https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2026-mwb/Vida-y-Ministerio-Cristianos-5-a-11-de-octubre-de-2026/'}
{'semana': '12-18 de octubre', 'url': 'https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2026-mwb/Vida-y-Ministerio-Cristianos-12-a-18-de-octubre-de-2026/'}
{'semana': '19-25 de octubre', 'url': 'https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2026-mwb/Vida-y-Ministerio-Cristianos-19-a-25-de-octubre-de-2026/'}

In [ ]:
df_weeks = pd.DataFrame(weeks_data)

df_weeks.head()

                semana                                                url
0   7-13 de septiembre  https://www.jw.org/es/biblioteca/guia-activida...
1  14-20 de septiembre  https://www.jw.org/es/biblioteca/guia-activida...
2  21-27 de septiembre  https://www.jw.org/es/biblioteca/guia-activida...
3      5-11 de octubre  https://www.jw.org/es/biblioteca/guia-activida...
4     12-18 de octubre  https://www.jw.org/es/biblioteca/guia-activida...

In [ ]:
df_weeks = df_weeks.drop_duplicates()

df_weeks.reset_index(drop=True, inplace=True)

df_weeks

                semana                                                url
0   7-13 de septiembre  https://www.jw.org/es/biblioteca/guia-activida...
1  14-20 de septiembre  https://www.jw.org/es/biblioteca/guia-activida...
2  21-27 de septiembre  https://www.jw.org/es/biblioteca/guia-activida...
3      5-11 de octubre  https://www.jw.org/es/biblioteca/guia-activida...
4     12-18 de octubre  https://www.jw.org/es/biblioteca/guia-activida...
5     19-25 de octubre  https://www.jw.org/es/biblioteca/guia-activida...

In [ ]:
week_url = df_weeks.iloc[0]["url"]

print(week_url)

https://www.jw.org/es/biblioteca/guia-actividades-reunion-testigos-jehova/septiembre-octubre-2026-mwb/Vida-y-Ministerio-Cristianos-7-a-13-de-septiembre-de-2026/

In [ ]:
html_week = requests.get(week_url).text

soup_week = BeautifulSoup(html_week, "lxml")

In [ ]:
for tag in soup_week.find_all(["h1", "h2", "h3", "h4"]):
    texto = tag.text.strip()

    if texto:
        print(texto)

Testigos de Jehová
Vida y Ministerio Cristianos (7 a 13 de septiembre de 2026)
7-13 de septiembre
JEREMÍAS 32, 33
Canción 1 y oración | Palabras de introducción (1 min.)
TESOROS DE LA BIBLIA
1. Meditar en las cualidades de Jehová fortalece nuestra fe
2. Busquemos perlas escondidas
3. Lectura de la Biblia
SEAMOS MEJORES MAESTROS
4. Empiece conversaciones
5. Empiece conversaciones
6. Haga revisitas
NUESTRA VIDA CRISTIANA
Canción 128
7. En esta campaña, ni un golpe al aire
8. Estudio bíblico de la congregación
Palabras de conclusión (3 mins.) | Canción 143 y oración
Seleccione un idioma
Compartir

In [ ]:
texto_completo = soup_week.get_text("\n")

print(texto_completo[:5000])

Vida y Ministerio Cristianos: 7 a 13 de septiembre de 2026




































































































































































































































































































































































































































































































































































































































Ir al contenido










Ir al índice


















JW.ORG














Cambiar idioma del sitio












CERRAR













            Iniciar sesión
            (abre una nueva ventana)













Búsquedas en jw.org
















MOSTRAR MENÚ













                           INICIO














         ENSEÑANZAS BÍBLICAS















Mostrar más

















                  Preguntas sobre la Biblia














                  Textos bíblicos explicados














                  Curso de la Biblia














                  Ayudas para estudiar la Biblia














                  Felicidad y paz interior














                  El matrimonio y la familia














                  Adolescentes y jóvenes adultos














                  Niños














                  Fe en Dios














                  La Biblia y la ciencia














                  La Biblia y la historia
















         BIBLIOTECA















Mostrar más

















                  Biblias














                  Libros














                  Folletos














                  Tratados e invitaciones














                  Catálogo de artículos














                  Revistas














                  Guía de actividades














                  Ministerio del Reino














                  Programas














                  Índices














                  Pautas


















                     JW Broadcasting
®















                  Videos














                  Música














                  Obras teatrales en audio














                  Lecturas dramatizadas de la Biblia


















                  Biblioteca en línea



(abre una nueva ventana)















         NOTICIAS














         SOBRE NOSOTROS















Mostrar más

















                  Preguntas frecuentes














                  Solicite una visita














                  Contáctenos














                  Visitas a Betel














                  Reuniones














                  Conmemoración














                  Asambleas anuales














                  Qué hacemos














                  Experiencias














                  Por todo el mundo


















                  Donaciones



(abre una nueva ventana)



















                        INICIAR SESIÓN



(abre una nueva ventana)












CERRAR


































JW.ORG






Testigos de Jehová














Seleccionar idioma


español












Iniciar sesión


(abre una nueva ventana)


















Buscar




































INICIO












ENSEÑANZAS BÍBLICAS












Enseñanzas bíblicas
















Preguntas sobre la Biblia












Textos bíblicos explicados












Curso de la Biblia












Ayudas para estudiar la Biblia
















Felicidad y paz interior












El matrimonio y la familia












Adolescentes y jóvenes adultos












Niños
















Fe en Dios












La Biblia y la ciencia












La Biblia y la historia






















CERRAR


















BIBLIOTECA












Biblioteca
















Biblias












Libros












Folletos












Tratados e invitaciones












Catálogo de artículos
















Revistas












Guía de actividades












Ministerio del Reino












Programas

In [ ]:
lineas = texto_completo.split("\n")

for linea in lineas:

    linea = linea.strip()

    if re.match(r"^\d+\.", linea):
        print(linea)

1. Meditar en las cualidades de Jehová fortalece nuestra fe
2. Busquemos perlas escondidas
3. Lectura de la Biblia
4. Empiece conversaciones
5. Empiece conversaciones
6. Haga revisitas
7. En esta campaña, ni un golpe al aire
8. Estudio bíblico de la congregación

In [ ]:
for linea in lineas:

    if re.search(r"\(\d+\smin", linea):
        print(linea)

(1 min.)
(10 mins.)
(10 mins.)
(4 mins.)
(3 mins.) DE CASA EN CASA. Ofrezca un curso de la Biblia (
(4 mins.) PREDICACIÓN INFORMAL. Ofrezca un curso de la Biblia (
(5 mins.) DE CASA EN CASA. Ofrezca un curso de la Biblia (
(15 mins.) Análisis con el auditorio.
(30 mins.)
(3 mins.)

In [ ]:
for linea in lineas:

    if "Canción" in linea or "Cancion" in linea:
        print(linea)

Canción 1
Canción 128
Canción 143

In [ ]:
SECCIONES = [
    "TESOROS DE LA BIBLIA",
    "SEAMOS MEJORES MAESTROS",
    "NUESTRA VIDA CRISTIANA"
]

for linea in lineas:

    linea = linea.strip()

    if linea in SECCIONES:
        print("SECCIÓN:", linea)

SECCIÓN: TESOROS DE LA BIBLIA
SECCIÓN: SEAMOS MEJORES MAESTROS
SECCIÓN: NUESTRA VIDA CRISTIANA

In [ ]:
items = []

for linea in lineas:

    linea = linea.strip()

    if re.match(r"^\d+\.", linea):

        items.append(linea)

items

['1. Meditar en las cualidades de Jehová fortalece nuestra fe',
 '2. Busquemos perlas escondidas',
 '3. Lectura de la Biblia',
 '4. Empiece conversaciones',
 '5. Empiece conversaciones',
 '6. Haga revisitas',
 '7. En esta campaña, ni\xa0un golpe al aire',
 '8. Estudio bíblico de la congregación']

In [ ]:
duraciones = []

for linea in lineas:

    linea = linea.strip()

    if re.search(r"\(\d+\smin", linea):

        duraciones.append(linea)

duraciones

['(1 min.)',
 '(10 mins.)',
 '(10 mins.)',
 '(4 mins.)',
 '(3 mins.) DE CASA EN CASA. Ofrezca un curso de la Biblia (',
 '(4 mins.) PREDICACIÓN INFORMAL. Ofrezca un curso de la Biblia (',
 '(5 mins.) DE CASA EN CASA. Ofrezca un curso de la Biblia (',
 '(15 mins.) Análisis con el auditorio.',
 '(30 mins.)',
 '(3 mins.)']

In [ ]:
duraciones_limpias = []

for d in duraciones:

    m = re.search(r"(\d+)", d)

    if m:
        duraciones_limpias.append(int(m.group(1)))

duraciones_limpias

[1, 10, 10, 4, 3, 4, 5, 15, 30, 3]

In [ ]:
print("Items:", len(items))
print("Duraciones:", len(duraciones_limpias))

Items: 8
Duraciones: 10

In [ ]:
seccion_actual = None

items_estructurados = []

for linea in lineas:

    linea = linea.strip()

    if not linea:
        continue

    # detectar sección
    if linea in SECCIONES:
        seccion_actual = linea
        continue

    # detectar item
    if re.match(r"^\d+\.", linea):

        m = re.match(r"^(\d+)\.\s(.+)", linea)

        if m:

            numero = int(m.group(1))
            titulo = m.group(2)

            items_estructurados.append({
                "seccion": seccion_actual,
                "item_num": numero,
                "titulo": titulo
            })

items_estructurados

[{'seccion': 'TESOROS DE LA BIBLIA',
  'item_num': 1,
  'titulo': 'Meditar en las cualidades de Jehová fortalece nuestra fe'},
 {'seccion': 'TESOROS DE LA BIBLIA',
  'item_num': 2,
  'titulo': 'Busquemos perlas escondidas'},
 {'seccion': 'TESOROS DE LA BIBLIA',
  'item_num': 3,
  'titulo': 'Lectura de la Biblia'},
 {'seccion': 'SEAMOS MEJORES MAESTROS',
  'item_num': 4,
  'titulo': 'Empiece conversaciones'},
 {'seccion': 'SEAMOS MEJORES MAESTROS',
  'item_num': 5,
  'titulo': 'Empiece conversaciones'},
 {'seccion': 'SEAMOS MEJORES MAESTROS',
  'item_num': 6,
  'titulo': 'Haga revisitas'},
 {'seccion': 'NUESTRA VIDA CRISTIANA',
  'item_num': 7,
  'titulo': 'En esta campaña, ni\xa0un golpe al aire'},
 {'seccion': 'NUESTRA VIDA CRISTIANA',
  'item_num': 8,
  'titulo': 'Estudio bíblico de la congregación'}]

In [ ]:
df_items = pd.DataFrame(items_estructurados)

df_items

,seccion,item_num,titulo
0,TESOROS DE LA BIBLIA,1,Meditar en las cualidades de Jehová fortalece ...
1,TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas
2,TESOROS DE LA BIBLIA,3,Lectura de la Biblia
3,SEAMOS MEJORES MAESTROS,4,Empiece conversaciones
4,SEAMOS MEJORES MAESTROS,5,Empiece conversaciones
5,SEAMOS MEJORES MAESTROS,6,Haga revisitas
6,NUESTRA VIDA CRISTIANA,7,"En esta campaña, ni un golpe al aire"
7,NUESTRA VIDA CRISTIANA,8,Estudio bíblico de la congregación

In [ ]:
df_items["semana"] = df_weeks.iloc[0]["semana"]

In [ ]:
df_items["issue"] = soup_issue.title.text

In [ ]:
df_items = df_items[
    [
        "issue",
        "semana",
        "seccion",
        "item_num",
        "titulo"
    ]
]

df_items

,issue,semana,seccion,item_num,titulo
0,Guía de actividades para la reunión Vida y Min...,7-13 de septiembre,TESOROS DE LA BIBLIA,1,Meditar en las cualidades de Jehová fortalece ...
1,Guía de actividades para la reunión Vida y Min...,7-13 de septiembre,TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas
2,Guía de actividades para la reunión Vida y Min...,7-13 de septiembre,TESOROS DE LA BIBLIA,3,Lectura de la Biblia
3,Guía de actividades para la reunión Vida y Min...,7-13 de septiembre,SEAMOS MEJORES MAESTROS,4,Empiece conversaciones
4,Guía de actividades para la reunión Vida y Min...,7-13 de septiembre,SEAMOS MEJORES MAESTROS,5,Empiece conversaciones
5,Guía de actividades para la reunión Vida y Min...,7-13 de septiembre,SEAMOS MEJORES MAESTROS,6,Haga revisitas
6,Guía de actividades para la reunión Vida y Min...,7-13 de septiembre,NUESTRA VIDA CRISTIANA,7,"En esta campaña, ni un golpe al aire"
7,Guía de actividades para la reunión Vida y Min...,7-13 de septiembre,NUESTRA VIDA CRISTIANA,8,Estudio bíblico de la congregación

In [ ]:
SECCIONES = [
    "TESOROS DE LA BIBLIA",
    "SEAMOS MEJORES MAESTROS",
    "NUESTRA VIDA CRISTIANA"
]

registros = []

seccion_actual = None
item_actual = None

In [ ]:
for linea in lineas:

    linea = linea.strip()

    if not linea:
        continue

    # -------------------------
    # detectar sección
    # -------------------------
    if linea in SECCIONES:

        seccion_actual = linea
        continue

    # -------------------------
    # detectar item
    # -------------------------
    m_item = re.match(r"^(\d+)\.\s(.+)", linea)

    if m_item:

        numero = int(m_item.group(1))
        titulo = m_item.group(2)

        item_actual = {
            "seccion": seccion_actual,
            "item_num": numero,
            "titulo": titulo,
            "minutos": None
        }

        registros.append(item_actual)

        continue

    # -------------------------
    # detectar duración
    # -------------------------
    m_min = re.search(r"\((\d+)\smin", linea)

    if m_min and item_actual is not None:

        minutos = int(m_min.group(1))

        # asignar duración al último item
        item_actual["minutos"] = minutos

In [ ]:
df_programa = pd.DataFrame(registros)

df_programa

,seccion,item_num,titulo,minutos
0,TESOROS DE LA BIBLIA,1,Meditar en las cualidades de Jehová fortalece ...,10
1,TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10
2,TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4
3,SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3
4,SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,4
5,SEAMOS MEJORES MAESTROS,6,Haga revisitas,5
6,NUESTRA VIDA CRISTIANA,7,"En esta campaña, ni un golpe al aire",15
7,NUESTRA VIDA CRISTIANA,8,Estudio bíblico de la congregación,3

In [ ]:
df_programa["semana"] = df_weeks.iloc[0]["semana"]

df_programa["url"] = week_url

In [ ]:
df_programa = df_programa[
    [
        "semana",
        "seccion",
        "item_num",
        "titulo",
        "minutos",
        "url"
    ]
]

df_programa

,semana,seccion,item_num,titulo,minutos,url
0,7-13 de septiembre,TESOROS DE LA BIBLIA,1,Meditar en las cualidades de Jehová fortalece ...,10,https://www.jw.org/es/biblioteca/guia-activida...
1,7-13 de septiembre,TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,https://www.jw.org/es/biblioteca/guia-activida...
2,7-13 de septiembre,TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,https://www.jw.org/es/biblioteca/guia-activida...
3,7-13 de septiembre,SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3,https://www.jw.org/es/biblioteca/guia-activida...
4,7-13 de septiembre,SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,4,https://www.jw.org/es/biblioteca/guia-activida...
5,7-13 de septiembre,SEAMOS MEJORES MAESTROS,6,Haga revisitas,5,https://www.jw.org/es/biblioteca/guia-activida...
6,7-13 de septiembre,NUESTRA VIDA CRISTIANA,7,"En esta campaña, ni un golpe al aire",15,https://www.jw.org/es/biblioteca/guia-activida...
7,7-13 de septiembre,NUESTRA VIDA CRISTIANA,8,Estudio bíblico de la congregación,3,https://www.jw.org/es/biblioteca/guia-activida...

In [ ]:
df_programa.to_csv("programa_semana.csv", index=False)

In [ ]:
from google.colab import files

files.download("programa_semana.csv")

In [ ]:
lectura_semanal = None

for linea in lineas:

    linea = linea.strip()

    # detectar referencias tipo:
    # JEREMÍAS 32, 33
    if re.match(r"^[A-ZÁÉÍÓÚÑ\s]+\d+", linea):

        lectura_semanal = linea
        break

print(lectura_semanal)

JEREMÍAS 32,

In [ ]:
canciones = []

for linea in lineas:

    linea = linea.strip()

    m = re.search(r"Canci[oó]n\s+(\d+)", linea)

    if m:

        canciones.append(int(m.group(1)))

canciones

[1, 128, 143]

In [ ]:
cancion_inicio = canciones[0] if len(canciones) > 0 else None
cancion_intermedia = canciones[1] if len(canciones) > 1 else None
cancion_final = canciones[2] if len(canciones) > 2 else None

print(cancion_inicio)
print(cancion_intermedia)
print(cancion_final)

1
128
143

In [ ]:
introduccion = None

for linea in lineas:

    if "Palabras de introducción" in linea:
        introduccion = linea
        break

introduccion

'y oración | Palabras de introducción'

In [ ]:
conclusion = None

for linea in lineas:

    if "Palabras de conclusión" in linea:
        conclusion = linea
        break

conclusion

'Palabras de conclusión '

In [ ]:
df_programa["lectura_semanal"] = lectura_semanal

df_programa["cancion_inicio"] = cancion_inicio
df_programa["cancion_intermedia"] = cancion_intermedia
df_programa["cancion_final"] = cancion_final

df_programa["introduccion"] = introduccion
df_programa["conclusion"] = conclusion

/tmp/ipykernel_1966/3223491712.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_programa["lectura_semanal"] = lectura_semanal
/tmp/ipykernel_1966/3223491712.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_programa["cancion_inicio"] = cancion_inicio
/tmp/ipykernel_1966/3223491712.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_programa["cancion_intermedia"] = cancion_intermedia
/tmp/ipykernel_1966/3223491712.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_programa["cancion_final"] = cancion_final
/tmp/ipykernel_1966/3223491712.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_programa["introduccion"] = introduccion
/tmp/ipykernel_1966/3223491712.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_programa["conclusion"] = conclusion

In [ ]:
df_programa.head()

,semana,seccion,item_num,titulo,minutos,url,lectura_semanal,cancion_inicio,cancion_intermedia,cancion_final,introduccion,conclusion
0,7-13 de septiembre,TESOROS DE LA BIBLIA,1,Meditar en las cualidades de Jehová fortalece ...,10,https://www.jw.org/es/biblioteca/guia-activida...,"JEREMÍAS 32,",1,128,143,y oración | Palabras de introducción,Palabras de conclusión
1,7-13 de septiembre,TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,https://www.jw.org/es/biblioteca/guia-activida...,"JEREMÍAS 32,",1,128,143,y oración | Palabras de introducción,Palabras de conclusión
2,7-13 de septiembre,TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,https://www.jw.org/es/biblioteca/guia-activida...,"JEREMÍAS 32,",1,128,143,y oración | Palabras de introducción,Palabras de conclusión
3,7-13 de septiembre,SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3,https://www.jw.org/es/biblioteca/guia-activida...,"JEREMÍAS 32,",1,128,143,y oración | Palabras de introducción,Palabras de conclusión
4,7-13 de septiembre,SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,4,https://www.jw.org/es/biblioteca/guia-activida...,"JEREMÍAS 32,",1,128,143,y oración | Palabras de introducción,Palabras de conclusión

In [ ]:
df_programa = df_programa[
    [
        "semana",
        "lectura_semanal",

        "cancion_inicio",
        "cancion_intermedia",
        "cancion_final",

        "introduccion",
        "conclusion",

        "seccion",
        "item_num",
        "titulo",
        "minutos",

        "url"
    ]
]

df_programa.head()

,semana,lectura_semanal,cancion_inicio,cancion_intermedia,cancion_final,introduccion,conclusion,seccion,item_num,titulo,minutos,url
0,7-13 de septiembre,"JEREMÍAS 32,",1,128,143,y oración | Palabras de introducción,Palabras de conclusión,TESOROS DE LA BIBLIA,1,Meditar en las cualidades de Jehová fortalece ...,10,https://www.jw.org/es/biblioteca/guia-activida...
1,7-13 de septiembre,"JEREMÍAS 32,",1,128,143,y oración | Palabras de introducción,Palabras de conclusión,TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,https://www.jw.org/es/biblioteca/guia-activida...
2,7-13 de septiembre,"JEREMÍAS 32,",1,128,143,y oración | Palabras de introducción,Palabras de conclusión,TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,https://www.jw.org/es/biblioteca/guia-activida...
3,7-13 de septiembre,"JEREMÍAS 32,",1,128,143,y oración | Palabras de introducción,Palabras de conclusión,SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3,https://www.jw.org/es/biblioteca/guia-activida...
4,7-13 de septiembre,"JEREMÍAS 32,",1,128,143,y oración | Palabras de introducción,Palabras de conclusión,SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,4,https://www.jw.org/es/biblioteca/guia-activida...

In [ ]:
texto_plano = " ".join(lineas)

texto_plano[:1000]

'              Vida y Ministerio Cristianos: 7 a 13 de septiembre de 2026                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Ir al contenido           Ir al índice                   JW.ORG               Cambiar idioma del\xa0sitio             CERRAR                          Iniciar sesión             (abre una nueva ventana)                       Búsquedas en jw.org                 MOSTRAR MENÚ                                         INICI'

In [ ]:
m = re.search(
    r"([A-ZÁÉÍÓÚÑ]+(?:\s+[A-ZÁÉÍÓÚÑ]+)*\s+\d+,\s*\d+)",
    texto_plano
)

lectura_semanal = m.group(1) if m else None

print(lectura_semanal)

JEREMÍAS 32,   33

In [ ]:
m = re.search(
    r"(Palabras de introducción\s*\(\d+\s*min[s]?\.\))",
    texto_plano
)

introduccion = m.group(1) if m else None

print(introduccion)

Palabras de introducción   (1 min.)

In [ ]:
m = re.search(
    r"(Palabras de conclusión\s*\(\d+\s*min[s]?\.\))",
    texto_plano
)

conclusion = m.group(1) if m else None

print(conclusion)

Palabras de conclusión  (3 mins.)

In [ ]:
df_programa["lectura_semanal"] = lectura_semanal
df_programa["introduccion"] = introduccion
df_programa["conclusion"] = conclusion

In [ ]:
df_programa.head()

,semana,lectura_semanal,cancion_inicio,cancion_intermedia,cancion_final,introduccion,conclusion,seccion,item_num,titulo,minutos,url
0,7-13 de septiembre,"JEREMÍAS 32, 33",1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),TESOROS DE LA BIBLIA,1,Meditar en las cualidades de Jehová fortalece ...,10,https://www.jw.org/es/biblioteca/guia-activida...
1,7-13 de septiembre,"JEREMÍAS 32, 33",1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,https://www.jw.org/es/biblioteca/guia-activida...
2,7-13 de septiembre,"JEREMÍAS 32, 33",1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,https://www.jw.org/es/biblioteca/guia-activida...
3,7-13 de septiembre,"JEREMÍAS 32, 33",1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3,https://www.jw.org/es/biblioteca/guia-activida...
4,7-13 de septiembre,"JEREMÍAS 32, 33",1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,4,https://www.jw.org/es/biblioteca/guia-activida...

In [ ]:
for linea in lineas:

    linea = linea.strip()

    if re.search(r"\([A-Za-z].*?\)", linea):
        print(linea)

(abre una nueva ventana)
(abre una nueva ventana)
(abre una nueva ventana)
(abre una nueva ventana)
(abre una nueva ventana)
(abre una nueva ventana)
(abre una nueva ventana)
azerí (alfabeto cirílico)
changana (mozambique)
chino cantonés (simplificado)
chino cantonés (tradicional)
chino mandarín (simplificado)
chino mandarín (tradicional)
hamshen (armenio)
hamshen (cirílico)
hmong (blanco)
konkani (alfabeto latino)
kurdo kurmanyí (alfabeto cirílico)
ngäbere (o guaymí)
portugués (angola)
romaní de Macedonia (alfabeto cirílico)
serbio (alfabeto cirílico)
serbio (alfabeto latino)
(fragmento).
Lector de pantalla (RTF)
Anotador (BRL)
(abre una nueva ventana)
(abre una nueva ventana)
(abre una nueva ventana)
(abre una nueva ventana)
(abre una nueva ventana)

In [ ]:
TIPOS = [
    "DE CASA EN CASA",
    "PREDICACIÓN INFORMAL",
    "CURSO BÍBLICO",
]

for linea in lineas:

    linea = linea.strip()

    for t in TIPOS:

        if t in linea:
            print(linea)

In [ ]:
for linea in lineas:

    linea = linea.strip()

    if (
        "DE CASA EN CASA" in linea
        or "PREDICACIÓN INFORMAL" in linea
        or "CURSO" in linea
        or "Imd" in linea
        or "th" in linea
    ):
        print(linea)

th
(3 mins.) DE CASA EN CASA. Ofrezca un curso de la Biblia (
(4 mins.) PREDICACIÓN INFORMAL. Ofrezca un curso de la Biblia (
(5 mins.) DE CASA EN CASA. Ofrezca un curso de la Biblia (

In [ ]:
registros = []

seccion_actual = None
item_actual = None

In [ ]:
for i, linea in enumerate(lineas):

    linea = linea.strip()

    if not linea:
        continue

    # --------------------------------
    # detectar sección
    # --------------------------------
    if linea in SECCIONES:

        seccion_actual = linea
        continue

    # --------------------------------
    # detectar item
    # --------------------------------
    m_item = re.match(r"^(\d+)\.\s(.+)", linea)

    if m_item:

        numero = int(m_item.group(1))
        titulo = m_item.group(2)

        item_actual = {
            "seccion": seccion_actual,
            "item_num": numero,
            "titulo": titulo,
            "minutos": None,
            "tipo_actividad": None,
            "descripcion": None,
            "referencia": None
        }

        registros.append(item_actual)

        continue

    # --------------------------------
    # detectar duración
    # --------------------------------
    m_min = re.search(r"\((\d+)\s*min", linea)

    if m_min and item_actual is not None:

        item_actual["minutos"] = int(m_min.group(1))

        # guardar línea completa
        item_actual["descripcion"] = linea

        # --------------------------------
        # detectar tipo actividad
        # --------------------------------

        tipos = [
            "DE CASA EN CASA",
            "PREDICACIÓN INFORMAL",
            "CURSO BÍBLICO"
        ]

        for t in tipos:

            if t in linea:
                item_actual["tipo_actividad"] = t

        # --------------------------------
        # detectar referencia
        # --------------------------------

        refs = re.findall(r"\(([A-Za-z].*?)\)", linea)

        if refs:
            item_actual["referencia"] = " | ".join(refs)

In [ ]:
df_full = pd.DataFrame(registros)

df_full.head(10)

,seccion,item_num,titulo,minutos,tipo_actividad,descripcion,referencia
0,TESOROS DE LA BIBLIA,1,Meditar en las cualidades de Jehová fortalece ...,10,None,(10 mins.),None
1,TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,None,(10 mins.),None
2,TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,None,(4 mins.),None
3,SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3,DE CASA EN CASA,(3 mins.) DE CASA EN CASA. Ofrezca un curso de...,None
4,SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,4,PREDICACIÓN INFORMAL,(4 mins.) PREDICACIÓN INFORMAL. Ofrezca un cur...,None
5,SEAMOS MEJORES MAESTROS,6,Haga revisitas,5,DE CASA EN CASA,(5 mins.) DE CASA EN CASA. Ofrezca un curso de...,None
6,NUESTRA VIDA CRISTIANA,7,"En esta campaña, ni un golpe al aire",15,None,(15 mins.) Análisis con el auditorio.,None
7,NUESTRA VIDA CRISTIANA,8,Estudio bíblico de la congregación,3,None,(3 mins.),None

In [ ]:
df_full["semana"] = df_weeks.iloc[0]["semana"]

df_full["lectura_semanal"] = lectura_semanal

df_full["cancion_inicio"] = cancion_inicio
df_full["cancion_intermedia"] = cancion_intermedia
df_full["cancion_final"] = cancion_final

df_full["introduccion"] = introduccion
df_full["conclusion"] = conclusion

df_full["url"] = week_url

In [ ]:
df_full = df_full[
    [
        "semana",
        "lectura_semanal",

        "seccion",
        "item_num",
        "titulo",
        "minutos",

        "tipo_actividad",
        "referencia",
        "descripcion",

        "cancion_inicio",
        "cancion_intermedia",
        "cancion_final",

        "introduccion",
        "conclusion",

        "url"
    ]
]

df_full.head(20)

,semana,lectura_semanal,seccion,item_num,titulo,minutos,tipo_actividad,referencia,descripcion,cancion_inicio,cancion_intermedia,cancion_final,introduccion,conclusion,url
0,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,1,Meditar en las cualidades de Jehová fortalece ...,10,None,None,(10 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
1,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,None,None,(10 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
2,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,None,None,(4 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
3,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3,DE CASA EN CASA,None,(3 mins.) DE CASA EN CASA. Ofrezca un curso de...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
4,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,4,PREDICACIÓN INFORMAL,None,(4 mins.) PREDICACIÓN INFORMAL. Ofrezca un cur...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
5,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,6,Haga revisitas,5,DE CASA EN CASA,None,(5 mins.) DE CASA EN CASA. Ofrezca un curso de...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
6,7-13 de septiembre,"JEREMÍAS 32, 33",NUESTRA VIDA CRISTIANA,7,"En esta campaña, ni un golpe al aire",15,None,None,(15 mins.) Análisis con el auditorio.,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
7,7-13 de septiembre,"JEREMÍAS 32, 33",NUESTRA VIDA CRISTIANA,8,Estudio bíblico de la congregación,3,None,None,(3 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...

In [ ]:
def parsear_semana(week_url, semana):

    html = requests.get(week_url).text

    soup = BeautifulSoup(html, "lxml")

    texto = soup.get_text("\n")

    lineas = [x.strip() for x in texto.split("\n") if x.strip()]

    texto_plano = " ".join(lineas)

    # ==================================================
    # LECTURA SEMANAL
    # ==================================================

    m = re.search(
        r"([A-ZÁÉÍÓÚÑ]+(?:\s+[A-ZÁÉÍÓÚÑ]+)*\s+\d+,\s*\d+)",
        texto_plano
    )

    lectura_semanal = m.group(1) if m else None

    # ==================================================
    # CANCIONES
    # ==================================================

    canciones = re.findall(r"Canci[oó]n\s+(\d+)", texto_plano)

    canciones = [int(x) for x in canciones]

    cancion_inicio = canciones[0] if len(canciones) > 0 else None
    cancion_intermedia = canciones[1] if len(canciones) > 1 else None
    cancion_final = canciones[2] if len(canciones) > 2 else None

    # ==================================================
    # INTRODUCCIÓN
    # ==================================================

    m = re.search(
        r"(Palabras de introducción\s*\(\d+\s*min[s]?\.\))",
        texto_plano
    )

    introduccion = m.group(1) if m else None

    # ==================================================
    # CONCLUSIÓN
    # ==================================================

    m = re.search(
        r"(Palabras de conclusión\s*\(\d+\s*min[s]?\.\))",
        texto_plano
    )

    conclusion = m.group(1) if m else None

    # ==================================================
    # PARSER ITEMS
    # ==================================================

    SECCIONES = [
        "TESOROS DE LA BIBLIA",
        "SEAMOS MEJORES MAESTROS",
        "NUESTRA VIDA CRISTIANA"
    ]

    registros = []

    seccion_actual = None
    item_actual = None

    for linea in lineas:

        # ----------------------------------------
        # detectar sección
        # ----------------------------------------

        if linea in SECCIONES:

            seccion_actual = linea
            continue

        # ----------------------------------------
        # detectar item
        # ----------------------------------------

        m_item = re.match(r"^(\d+)\.\s(.+)", linea)

        if m_item:

            numero = int(m_item.group(1))
            titulo = m_item.group(2)

            item_actual = {
                "semana": semana,
                "lectura_semanal": lectura_semanal,

                "seccion": seccion_actual,
                "item_num": numero,
                "titulo": titulo,

                "minutos": None,

                "tipo_actividad": None,
                "referencia": None,
                "descripcion": None,

                "cancion_inicio": cancion_inicio,
                "cancion_intermedia": cancion_intermedia,
                "cancion_final": cancion_final,

                "introduccion": introduccion,
                "conclusion": conclusion,

                "url": week_url
            }

            registros.append(item_actual)

            continue

        # ----------------------------------------
        # detectar duración
        # ----------------------------------------

        m_min = re.search(r"\((\d+)\s*min", linea)

        if m_min and item_actual is not None:

            item_actual["minutos"] = int(m_min.group(1))

            item_actual["descripcion"] = linea

            # ----------------------------------------
            # tipo actividad
            # ----------------------------------------

            tipos = [
                "DE CASA EN CASA",
                "PREDICACIÓN INFORMAL",
                "CURSO BÍBLICO"
            ]

            for t in tipos:

                if t in linea:
                    item_actual["tipo_actividad"] = t

            # ----------------------------------------
            # referencias
            # ----------------------------------------

            refs = re.findall(r"\(([A-Za-z].*?)\)", linea)

            if refs:
                item_actual["referencia"] = " | ".join(refs)

    return pd.DataFrame(registros)

In [ ]:
df_test = parsear_semana(
    df_weeks.iloc[0]["url"],
    df_weeks.iloc[0]["semana"]
)

df_test.head()

,semana,lectura_semanal,seccion,item_num,titulo,minutos,tipo_actividad,referencia,descripcion,cancion_inicio,cancion_intermedia,cancion_final,introduccion,conclusion,url
0,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,1,Meditar en las cualidades de Jehová fortalece ...,10,None,None,(10 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
1,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,None,None,(10 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
2,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,None,None,(4 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
3,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3,DE CASA EN CASA,None,(3 mins.) DE CASA EN CASA. Ofrezca un curso de...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
4,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,4,PREDICACIÓN INFORMAL,None,(4 mins.) PREDICACIÓN INFORMAL. Ofrezca un cur...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...

In [ ]:
dfs = []

for i, row in df_weeks.iterrows():

    semana = row["semana"]
    url = row["url"]

    print(f"Procesando: {semana}")

    try:

        df_temp = parsear_semana(url, semana)

        dfs.append(df_temp)

    except Exception as e:

        print("ERROR:", semana)
        print(e)

Procesando: 7-13 de septiembre
Procesando: 14-20 de septiembre
Procesando: 21-27 de septiembre
Procesando: 5-11 de octubre
Procesando: 12-18 de octubre
Procesando: 19-25 de octubre

In [ ]:
df_historico = pd.concat(dfs, ignore_index=True)

df_historico.head(20)

,semana,lectura_semanal,seccion,item_num,titulo,minutos,tipo_actividad,referencia,descripcion,cancion_inicio,cancion_intermedia,cancion_final,introduccion,conclusion,url
0,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,1,Meditar en las cualidades de Jehová fortalece ...,10,None,None,(10 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
1,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,None,None,(10 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
2,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,None,None,(4 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
3,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3,DE CASA EN CASA,None,(3 mins.) DE CASA EN CASA. Ofrezca un curso de...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
4,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,4,PREDICACIÓN INFORMAL,None,(4 mins.) PREDICACIÓN INFORMAL. Ofrezca un cur...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
5,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,6,Haga revisitas,5,DE CASA EN CASA,None,(5 mins.) DE CASA EN CASA. Ofrezca un curso de...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
6,7-13 de septiembre,"JEREMÍAS 32, 33",NUESTRA VIDA CRISTIANA,7,"En esta campaña, ni un golpe al aire",15,None,None,(15 mins.) Análisis con el auditorio.,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
7,7-13 de septiembre,"JEREMÍAS 32, 33",NUESTRA VIDA CRISTIANA,8,Estudio bíblico de la congregación,3,None,None,(3 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
8,14-20 de septiembre,"JEREMÍAS 34, 35",TESOROS DE LA BIBLIA,1,Jehová recompensa a los que siempre le obedecen,10,None,None,(10 mins.),161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
9,14-20 de septiembre,"JEREMÍAS 34, 35",TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,None,None,(10 mins.),161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
10,14-20 de septiembre,"JEREMÍAS 34, 35",TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,None,None,(4 mins.),161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
11,14-20 de septiembre,"JEREMÍAS 34, 35",SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,2,DE CASA EN CASA,None,(2 mins.) DE CASA EN CASA. Ofrezca un curso de...,161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
12,14-20 de septiembre,"JEREMÍAS 34, 35",SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,2,DE CASA EN CASA,None,(2 mins.) DE CASA EN CASA. Ofrezca un curso de...,161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
13,14-20 de septiembre,"JEREMÍAS 34, 35",SEAMOS MEJORES MAESTROS,6,Haga revisitas,3,PREDICACIÓN INFORMAL,None,(3 mins.) PREDICACIÓN INFORMAL. Ofrézcale un c...,161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
14,14-20 de septiembre,"JEREMÍAS 34, 35",SEAMOS MEJORES MAESTROS,7,Haga discípulos,4,None,None,(4 mins.) Converse con su estudiante de la Bib...,161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
15,14-20 de septiembre,"JEREMÍAS 34, 35",NUESTRA VIDA CRISTIANA,8,El autocontrol nos ayuda a obedecer,9,None,None,(9 mins.) Análisis con el auditorio.,161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
16,14-20 de septiembre,"JEREMÍAS 34, 35",NUESTRA VIDA CRISTIANA,10,Estudio bíblico de la congregación,3,None,None,(3 mins.),161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
17,21-27 de septiembre,"JEREMÍAS 36, 37",TESOROS DE LA BIBLIA,1,Jehová ayuda a quienes apoyan su Reino,10,None,None,(10 mins.),74,142,134,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
18,21-27 de septiembre,"JEREMÍAS 36, 37",TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,None,None,(10 mins.),74,142,134,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
19,21-27 de septiembre,"JEREMÍAS 36, 37",TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,None,None,(4 mins.),74,142,134,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...

In [ ]:
df_historico.shape

(51, 15)

In [ ]:
df_historico["semana"].unique()

array(['7-13 de septiembre', '14-20 de septiembre', '21-27 de septiembre',
       '5-11 de octubre', '12-18 de octubre', '19-25 de octubre'],
      dtype=object)

In [ ]:
df_historico.to_csv(
    "historico_reuniones_jw.csv",
    index=False
)

In [ ]:
from google.colab import files

files.download("historico_reuniones_jw.csv")

In [ ]:
print("ANTES:", df_historico.shape)

ANTES: (51, 15)

In [ ]:
duplicados = df_historico[
    df_historico.duplicated(
        subset=[
            "semana",
            "seccion",
            "item_num",
            "titulo"
        ],
        keep=False
    )
]

duplicados

Empty DataFrame
Columns: [semana, lectura_semanal, seccion, item_num, titulo, minutos, tipo_actividad, referencia, descripcion, cancion_inicio, cancion_intermedia, cancion_final, introduccion, conclusion, url]
Index: []

In [ ]:
len(duplicados)

0

In [ ]:
df_historico

,semana,lectura_semanal,seccion,item_num,titulo,minutos,tipo_actividad,referencia,descripcion,cancion_inicio,cancion_intermedia,cancion_final,introduccion,conclusion,url
0,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,1,Meditar en las cualidades de Jehová fortalece ...,10,None,None,(10 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
1,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,None,None,(10 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
2,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,None,None,(4 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
3,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3,DE CASA EN CASA,None,(3 mins.) DE CASA EN CASA. Ofrezca un curso de...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
4,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,4,PREDICACIÓN INFORMAL,None,(4 mins.) PREDICACIÓN INFORMAL. Ofrezca un cur...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
5,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,6,Haga revisitas,5,DE CASA EN CASA,None,(5 mins.) DE CASA EN CASA. Ofrezca un curso de...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
6,7-13 de septiembre,"JEREMÍAS 32, 33",NUESTRA VIDA CRISTIANA,7,"En esta campaña, ni un golpe al aire",15,None,None,(15 mins.) Análisis con el auditorio.,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
7,7-13 de septiembre,"JEREMÍAS 32, 33",NUESTRA VIDA CRISTIANA,8,Estudio bíblico de la congregación,3,None,None,(3 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
8,14-20 de septiembre,"JEREMÍAS 34, 35",TESOROS DE LA BIBLIA,1,Jehová recompensa a los que siempre le obedecen,10,None,None,(10 mins.),161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
9,14-20 de septiembre,"JEREMÍAS 34, 35",TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,None,None,(10 mins.),161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
10,14-20 de septiembre,"JEREMÍAS 34, 35",TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,None,None,(4 mins.),161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
11,14-20 de septiembre,"JEREMÍAS 34, 35",SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,2,DE CASA EN CASA,None,(2 mins.) DE CASA EN CASA. Ofrezca un curso de...,161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
12,14-20 de septiembre,"JEREMÍAS 34, 35",SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,2,DE CASA EN CASA,None,(2 mins.) DE CASA EN CASA. Ofrezca un curso de...,161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
13,14-20 de septiembre,"JEREMÍAS 34, 35",SEAMOS MEJORES MAESTROS,6,Haga revisitas,3,PREDICACIÓN INFORMAL,None,(3 mins.) PREDICACIÓN INFORMAL. Ofrézcale un c...,161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
14,14-20 de septiembre,"JEREMÍAS 34, 35",SEAMOS MEJORES MAESTROS,7,Haga discípulos,4,None,None,(4 mins.) Converse con su estudiante de la Bib...,161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
15,14-20 de septiembre,"JEREMÍAS 34, 35",NUESTRA VIDA CRISTIANA,8,El autocontrol nos ayuda a obedecer,9,None,None,(9 mins.) Análisis con el auditorio.,161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
16,14-20 de septiembre,"JEREMÍAS 34, 35",NUESTRA VIDA CRISTIANA,10,Estudio bíblico de la congregación,3,None,None,(3 mins.),161,121,28,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
17,21-27 de septiembre,"JEREMÍAS 36, 37",TESOROS DE LA BIBLIA,1,Jehová ayuda a quienes apoyan su Reino,10,None,None,(10 mins.),74,142,134,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
18,21-27 de septiembre,"JEREMÍAS 36, 37",TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,None,None,(10 mins.),74,142,134,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
19,21-27 de septiembre,"JEREMÍAS 36, 37",TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,None,None,(4 mins.),74,142,134,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
20,21-27 de septiembre,"JEREMÍAS 36, 37",SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3,None,None,(3 mins.) PREDICACIÓN PÚBLICA. Ofrézcale un cu...,74,142,134,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
21,21-27 de septiembre,"JEREMÍAS 36, 37",SEAMOS MEJORES MAESTROS,5,Haga revisitas,4,DE CASA EN CASA,None,(4 mins.) DE CASA EN CASA. Ofrézcale un curso ...,74,142,134,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
22,21-27 de septiembre,"JEREMÍAS 36, 37",SEAMOS MEJORES MAESTROS,6,¿Qué diría?,6,DE CASA EN CASA,None,(6 mins.) Análisis con el auditorio. DE CASA E...,74,142,134,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
23,21-27 de septiembre,"JEREMÍAS 36, 37",NUESTRA VIDA CRISTIANA,7,Seamos siempre neutrales en nuestro corazón,15,None,None,(15 mins.) Análisis con el auditorio.,74,142,134,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
24,21-27 de septiembre,"JEREMÍAS 36, 37",NUESTRA VIDA CRISTIANA,8,Estudio bíblico de la congregación,3,None,None,(3 mins.),74,142,134,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
25,5-11 de octubre,"JEREMÍAS 40, 41",TESOROS DE LA BIBLIA,1,Tengamos un punto de vista equilibrado de la p...,10,None,None,(10 mins.),33,17,38,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
26,5-11 de octubre,"JEREMÍAS 40, 41",TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,None,None,(10 mins.),33,17,38,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
27,5-11 de octubre,"JEREMÍAS 40, 41",TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,None,None,(4 mins.),33,17,38,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
28,5-11 de octubre,"JEREMÍAS 40, 41",SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,2,DE CASA EN CASA,None,(2 mins.) DE CASA EN CASA. (,33,17,38,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
29,5-11 de octubre,"JEREMÍAS 40, 41",SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,2,PREDICACIÓN INFORMAL,None,(2 mins.) PREDICACIÓN INFORMAL. (,33,17,38,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
30,5-11 de octubre,"JEREMÍAS 40, 41",SEAMOS MEJORES MAESTROS,6,Empiece conversaciones,4,None,None,(4 mins.) PREDICACIÓN PÚBLICA. Una persona se ...,33,17,38,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
31,5-11 de octubre,"JEREMÍAS 40, 41",SEAMOS MEJORES MAESTROS,7,Explique sus creencias,3,None,None,(3 mins.) Escenificación.,33,17,38,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
32,5-11 de octubre,"JEREMÍAS 40, 41",NUESTRA VIDA CRISTIANA,8,Jehová protege a las viudas,15,None,None,(15 mins.) Análisis con el auditorio.,33,17,38,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
33,5-11 de octubre,"JEREMÍAS 40, 41",NUESTRA VIDA CRISTIANA,9,Estudio bíblico de la congregación,3,None,None,(3 mins.),33,17,38,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
34,12-18 de octubre,None,TESOROS DE LA BIBLIA,1,Pidieron guía y luego la rechazaron,10,None,None,(10 mins.),103,47,129,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
35,12-18 de octubre,None,TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,None,None,(10 mins.),103,47,129,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
36,12-18 de octubre,None,TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,None,None,(4 mins.),103,47,129,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
37,12-18 de octubre,None,SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3,PREDICACIÓN INFORMAL,None,(3 mins.) PREDICACIÓN INFORMAL. (,103,47,129,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
38,12-18 de octubre,None,SEAMOS MEJORES MAESTROS,5,Haga revisitas,4,DE CASA EN CASA,None,(4 mins.) DE CASA EN CASA. Utilice una de las ...,103,47,129,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
39,12-18 de octubre,None,SEAMOS MEJORES MAESTROS,6,¿Qué diría?,6,PREDICACIÓN INFORMAL,None,(6 mins.) Análisis con el auditorio. PREDICACI...,103,47,129,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
40,12-18 de octubre,None,NUESTRA VIDA CRISTIANA,7,Necesidades de la congregación,15,None,None,(15 mins.),103,47,129,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
41,12-18 de octubre,None,NUESTRA VIDA CRISTIANA,8,Estudio bíblico de la congregación,3,None,None,(3 mins.),103,47,129,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
42,19-25 de octubre,"JEREMÍAS 45, 46",TESOROS DE LA BIBLIA,1,La esperanza es clave para estar contentos,10,None,None,(10 mins.),21,117,87,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
43,19-25 de octubre,"JEREMÍAS 45, 46",TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,None,None,(10 mins.),21,117,87,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
44,19-25 de octubre,"JEREMÍAS 45, 46",TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,None,None,(4 mins.),21,117,87,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
45,19-25 de octubre,"JEREMÍAS 45, 46",SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3,PREDICACIÓN INFORMAL,None,(3 mins.) PREDICACIÓN INFORMAL. Empiece una co...,21,117,87,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
46,19-25 de octubre,"JEREMÍAS 45, 46",SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,2,DE CASA EN CASA,None,(2 mins.) DE CASA EN CASA. La persona está eno...,21,117,87,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
47,19-25 de octubre,"JEREMÍAS 45, 46",SEAMOS MEJORES MAESTROS,6,Empiece conversaciones,2,DE CASA EN CASA,None,(2 mins.) DE CASA EN CASA. La persona que abre...,21,117,87,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
48,19-25 de octubre,"JEREMÍAS 45, 46",SEAMOS MEJORES MAESTROS,7,Discurso,4,None,None,(4 mins.),21,117,87,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
49,19-25 de octubre,"JEREMÍAS 45, 46",NUESTRA VIDA CRISTIANA,8,“No se olviden [...] de compartir lo que tienen”,15,None,None,(15 mins.) Análisis con el auditorio.,21,117,87,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
50,19-25 de octubre,"JEREMÍAS 45, 46",NUESTRA VIDA CRISTIANA,9,Estudio bíblico de la congregación,3,None,None,(3 mins.),21,117,87,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...

In [ ]:
df_weeks

                semana                                                url
0   7-13 de septiembre  https://www.jw.org/es/biblioteca/guia-activida...
1  14-20 de septiembre  https://www.jw.org/es/biblioteca/guia-activida...
2  21-27 de septiembre  https://www.jw.org/es/biblioteca/guia-activida...
3      5-11 de octubre  https://www.jw.org/es/biblioteca/guia-activida...
4     12-18 de octubre  https://www.jw.org/es/biblioteca/guia-activida...
5     19-25 de octubre  https://www.jw.org/es/biblioteca/guia-activida...

In [ ]:
cols = [
    "semana",
    "titulo",
    "minutos",
    "tipo_actividad"
]

duplicados = df_full[
    df_full.duplicated(
        subset=cols,
        keep=False
    )
]

duplicados.sort_values(cols)

Empty DataFrame
Columns: [semana, lectura_semanal, seccion, item_num, titulo, minutos, tipo_actividad, referencia, descripcion, cancion_inicio, cancion_intermedia, cancion_final, introduccion, conclusion, url]
Index: []

In [ ]:
%whos

Variable                                Type                    Data/Info
-------------------------------------------------------------------------
BASE_URL                                str                     https://www.jw.org
BeautifulSoup                           type                    <class 'bs4.BeautifulSoup'>
Dict                                    _SpecialGenericAlias    typing.Dict
HEADERS                                 dict                    n=1
IN_COLAB                                bool                    True
LIBROS_BIBLIA                           tuple                   n=56
List                                    _SpecialGenericAlias    typing.List
MAX_REINTENTOS                          int                     3
MAX_RETRIES                             int                     3
MESES_VALIDOS                           list                    n=6
Optional                                _SpecialForm            typing.Optional
PATRONES                                dict                    n=5
PATRON_CANCION                          Pattern                 re.compile('Canción\\s+(\\d+)', re.IGNORECASE)
PATRON_FECHA                            Pattern                 re.compile('\\d{1,2}.*de\\s+\\w+', re.IGNORECASE)
PATRON_PARTE                            Pattern                 re.compile('^\\d+\\.\\s*(<...>+)\\s*min', re.MULTILINE)
PATRON_SEMANA                           Pattern                 re.compile('\\d{4}')
PATTERN_CANCION                         Pattern                 re.compile('Canci[oó]n\\s+(\\d+)', re.IGNORECASE)
PATTERN_FECHA                           Pattern                 re.compile('\\d{1,2}\\s*-<...>ciembre)', re.IGNORECASE)
Path                                    type                    <class 'pathlib.Path'>
RATE_LIMIT_DELAY                        float                   1.5
RETRY_BACKOFF                           int                     2
SECCIONES                               list                    n=3
SHEETS_DISPONIBLE                       bool                    True
SPANISH_MONTHS                          str                     enero|febrero|marzo|abril<...>tubre|noviembre|diciembre
TIMEOUT                                 int                     30
Tuple                                   _TupleType              typing.Tuple
URL                                     str                     https://www.jw.org/es/bib<...>-reunion-testigos-jehova/
a                                       Tag                     <a class="jsPrivacySettin<...>URACIÓN DE PRIVACIDAD</a>
auth                                    module                  <module 'google.colab.aut<...>es/google/colab/auth.py'>
base                                    str                     https://www.jw.org
cancion_final                           int                     143
cancion_inicio                          int                     1
cancion_intermedia                      int                     128
canciones                               list                    n=3
cols                                    list                    n=4
conclusion                              str                     Palabras de conclusión  (3 mins.)
conectar_google_sheets                  function                <function conectar_google<...>sheets at 0x7ee27b4af2e0>
crear_plantilla_sheets                  function                <function crear_plantilla<...>sheets at 0x7ee27cecb100>
d                                       str                     (3 mins.)
data                                    list                    n=0
datetime                                type                    <class 'datetime.datetime'>
datos                                   list                    n=52
default                                 function                <function default at 0x7ee27c916de0>
df_full                                 DataFrame                              semana    <...>ioteca/guia-activida...
df_historico                            DataFrame                                semana  <...>ioteca/guia-activida...
df_issues                               DataFrame                                        <...>blioteca/guia-activida...
df_items                                DataFrame                                        <...>lico de la congregación
df_links                                DataFrame                                        <...>ioteca/guia-activida...
df_programa                             DataFrame                              semana    <...>ioteca/guia-activida...
df_temp                                 DataFrame                            semana  lect<...>ioteca/guia-activida...
df_test                                 DataFrame                              semana  le<...>ioteca/guia-activida...
df_weeks                                DataFrame                               semana   <...>blioteca/guia-activida...
dfs                                     list                    n=6
duplicados                              DataFrame               Empty DataFrame\nColumns:<...>nclusion, url]\nIndex: []
duraciones                              list                    n=10
duraciones_limpias                      list                    n=10
e                                       dict                    n=2
encontrar_posicion_cancion_intermedia   function                <function encontrar_posic<...>rmedia at 0x7ee27cecaf20>
enlaces                                 list                    n=52
exportar_csv                            function                <function exportar_csv at 0x7ee27c915d00>
extract_html                            function                <function extract_html at 0x7ee27b3b6520>
extract_links                           function                <function extract_links at 0x7ee27b3b7420>
extraer_canciones                       function                <function extraer_canciones at 0x7ee27b3b5580>
extraer_datos                           function                <function extraer_datos at 0x7ee27b3b5440>
extraer_datos_reunion                   function                <function extraer_datos_r<...>eunion at 0x7ee27cecb060>
extraer_fecha                           function                <function extraer_fecha at 0x7ee27b3b4fe0>
extraer_fecha_correcta                  function                <function extraer_fecha_c<...>rrecta at 0x7ee27cd31440>
extraer_fecha_para_ordenar              function                <function extraer_fecha_p<...>rdenar at 0x7ee27cd33e20>
extraer_lectura                         function                <function extraer_lectura at 0x7ee27b3b4cc0>
extraer_lectura_biblica                 function                <function extraer_lectura<...>iblica at 0x7ee27cecad40>
extraer_palabras                        function                <function extraer_palabras at 0x7ee27b3b56c0>
extraer_partes                          function                <function extraer_partes at 0x7ee27b3b5620>
files                                   module                  <module 'google.colab.fil<...>s/google/colab/files.py'>
gspread                                 module                  <module 'gspread' from '/<...>ges/gspread/__init__.py'>
href                                    str                     https://www.jw.org/open?d<...>id=1011512&prefer=content
html_issue                              str                     <!DOCTYPE html>\n\n<html <...>script></body>\n</html>\n
html_week                               str                     <!DOCTYPE html>\n<html la<...>ript>\n</body>\n</html>\n
i                                       int                     5
introduccion                            str                     Palabras de introducción   (1 min.)
issue_url                               str                     https://www.jw.org/es/bib<...>tiembre-octubre-2026-mwb/
item_actual                             dict                    n=7
items                                   list                    n=8
items_estructurados                     list                    n=8
json                                    module                  <module 'json' from '/usr<...>on3.12/json/__init__.py'>
lectura_semanal                         str                     JEREMÍAS 32,   33
linea                                   str
lineas                                  list                    n=5583
link                                    Tag                     <a class="tertiaryButton <...>r por e-mail</span>\n</a>
links                                   ResultSet               [<a class="mobileLogo" hr<...> por e-mail</span>\n</a>]
load_csv                                function                <function load_csv at 0x7ee27b3b5120>
log                                     Logger                  <Logger __main__ (WARNING)>
logging                                 module                  <module 'logging' from '/<...>.12/logging/__init__.py'>
m                                       Match                   <re.Match object; span=(1<...>e conclusión  (3 mins.)'>
m_item                                  NoneType                None
m_min                                   NoneType                None
main                                    function                <function main at 0x7ee27b3b5800>
minutos                                 int                     3
mostrar_semanas_disponibles             function                <function mostrar_semanas<...>nibles at 0x7ee27cd33b00>
normalizar_url                          function                <function normalizar_url at 0x7ee27d45c7c0>
numero                                  int                     8
obtener_contenido                       function                <function obtener_contenido at 0x7ee27b3b5300>
obtener_enlaces                         function                <function obtener_enlaces at 0x7ee27b3b54e0>
obtener_enlaces_semanas                 function                <function obtener_enlaces<...>emanas at 0x7ee27b4aec00>
p                                       str                     /es/biblioteca/guia-activ<...>a/enero-febrero-2026-mwb/
parsear_semana                          function                <function parsear_semana at 0x7ee27d45da80>
pd                                      module                  <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
publicaciones                           list                    n=8
publicaciones_full                      list                    n=8
r                                       Response                <Response [200]>
re                                      module                  <module 're' from '/usr/l<...>thon3.12/re/__init__.py'>
refs                                    list                    n=0
registros                               list                    n=8
rellenar_sheets                         function                <function rellenar_sheets at 0x7ee27cecb1a0>
requests                                module                  <module 'requests' from '<...>es/requests/__init__.py'>
response                                Response                <Response [200]>
row                                     Series                  semana                   <...>.\nName: 5, dtype: object
run_etl                                 function                <function run_etl at 0x7ee27b3b72e0>
s                                       str                     7-13 de septiembre
seccion_actual                          str                     NUESTRA VIDA CRISTIANA
semana                                  str                     19-25 de octubre
semanas                                 list                    n=6
session                                 Session                 <requests.sessions.Sessio<...>object at 0x7ee27c34c800>
soup                                    BeautifulSoup           <!DOCTYPE html>\n<html di<...>script></body>\n</html>\n
soup_issue                              BeautifulSoup           <!DOCTYPE html>\n<html di<...>script></body>\n</html>\n
soup_week                               BeautifulSoup           <!DOCTYPE html>\n<html di<...>ript>\n</body>\n</html>\n
t                                       str                     CURSO BÍBLICO
tag                                     Tag                     <h3 class="itemName" rv-h<...>ml="state.itemName"></h3>
texto                                   str
texto_completo                          str                     \n\n\n\n\n\n\n\n\n\n\n\n\<...>n\n\n\n\n\n\n\n\n\n\n\n\n
texto_plano                             str                                   Vida y Mini<...>
time                                    module                  <module 'time' (built-in)>
tipos                                   list                    n=3
titulo                                  str                     Estudio bíblico de la congregación
transform                               function                <function transform at 0x7ee27b3b5260>
url                                     str                     https://www.jw.org/es/bib<...>-a-25-de-octubre-de-2026/
urljoin                                 function                <function urljoin at 0x7ee2b0533d80>
urlparse                                function                <function urlparse at 0x7ee2b0533060>
urlunparse                              function                <function urlunparse at 0x7ee2b0533b00>
visto                                   set                     set()
w                                       dict                    n=2
week_url                                str                     https://www.jw.org/es/bib<...>13-de-septiembre-de-2026/
weeks_data                              list                    n=6

In [ ]:
df_programa.columns.tolist()

['semana',
 'lectura_semanal',
 'cancion_inicio',
 'cancion_intermedia',
 'cancion_final',
 'introduccion',
 'conclusion',
 'seccion',
 'item_num',
 'titulo',
 'minutos',
 'url']

In [ ]:
df_full.columns.tolist()

['semana',
 'lectura_semanal',
 'seccion',
 'item_num',
 'titulo',
 'minutos',
 'tipo_actividad',
 'referencia',
 'descripcion',
 'cancion_inicio',
 'cancion_intermedia',
 'cancion_final',
 'introduccion',
 'conclusion',
 'url']

In [ ]:
def limpiar_texto(x):
    if isinstance(x, str):
        return (
            x.replace("\xa0", " ")
             .strip()
        )
    return x

df_programa = df_programa.applymap(limpiar_texto)

/tmp/ipykernel_1966/1168430455.py:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_programa = df_programa.applymap(limpiar_texto)

In [ ]:
cols_logicas = [
    "semana",
    "seccion",
    "titulo",
    "minutos",
    "tipo_actividad"
]

duplicados = df_full[
    df_full.duplicated(
        subset=cols_logicas,
        keep=False
    )
]

duplicados.sort_values(cols_logicas)

Empty DataFrame
Columns: [semana, lectura_semanal, seccion, item_num, titulo, minutos, tipo_actividad, referencia, descripcion, cancion_inicio, cancion_intermedia, cancion_final, introduccion, conclusion, url]
Index: []

In [ ]:
cols_logicas = [
    "semana",
    "seccion",
    "titulo",
    "minutos",
    "tipo_actividad"
]

df_full = df_full.drop_duplicates(
    subset=cols_logicas
)

In [ ]:
df_full

,semana,lectura_semanal,seccion,item_num,titulo,minutos,tipo_actividad,referencia,descripcion,cancion_inicio,cancion_intermedia,cancion_final,introduccion,conclusion,url
0,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,1,Meditar en las cualidades de Jehová fortalece ...,10,None,None,(10 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
1,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,2,Busquemos perlas escondidas,10,None,None,(10 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
2,7-13 de septiembre,"JEREMÍAS 32, 33",TESOROS DE LA BIBLIA,3,Lectura de la Biblia,4,None,None,(4 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
3,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,4,Empiece conversaciones,3,DE CASA EN CASA,None,(3 mins.) DE CASA EN CASA. Ofrezca un curso de...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
4,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,5,Empiece conversaciones,4,PREDICACIÓN INFORMAL,None,(4 mins.) PREDICACIÓN INFORMAL. Ofrezca un cur...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
5,7-13 de septiembre,"JEREMÍAS 32, 33",SEAMOS MEJORES MAESTROS,6,Haga revisitas,5,DE CASA EN CASA,None,(5 mins.) DE CASA EN CASA. Ofrezca un curso de...,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
6,7-13 de septiembre,"JEREMÍAS 32, 33",NUESTRA VIDA CRISTIANA,7,"En esta campaña, ni un golpe al aire",15,None,None,(15 mins.) Análisis con el auditorio.,1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...
7,7-13 de septiembre,"JEREMÍAS 32, 33",NUESTRA VIDA CRISTIANA,8,Estudio bíblico de la congregación,3,None,None,(3 mins.),1,128,143,Palabras de introducción (1 min.),Palabras de conclusión (3 mins.),https://www.jw.org/es/biblioteca/guia-activida...